name: SaveSVG

on:
  schedule:
    - cron: "0 0 */2 * *"
  workflow_dispatch:

jobs:
  checkin:
    runs-on: ubuntu-latest
    steps:
      - uses: thinkasany/schedule@master
      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  savaSvg:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Build and publish
        run: |
          mkdir output
          cp /home/runner/work/_actions/thinkasany/schedule/master/dist/output/* output/
          
          git config user.name github-actions
          git config user.email github-actions@github.com
          
          git checkout output
          git add .
          git commit -m "Upload images"
          git push origin output   